### ISSUE TITLE
npm repository 0.1.9 version error.

### ISSUE THREAD

**Issue by GGYB** [pnext/three-loader#64]
hi, 
Thanks a lot for this lib.
It seem an error on npm repository 0.1.9.
```
Error: Cannot find module '@pnext/three-loader'
```
but it works well in 0.1.8, this is an [npm runkit example](https://npm.runkit.com/%40pnext%2Fthree-loader)

**Comment by fahadm** [comment]
This should be fixed after the 0.2.0 release.

**Comment by GGYB** [comment]
Thanks for your work. 👍
